default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: paresh
  password: vinsol

development:
  <<: *default
  database: MultiTenantApp_development

test:
  <<: *default
  database: MultiTenantApp_test

production:
  <<: *default
  database: MultiTenantApp_production
